# This workflow will build a package using Maven
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: [push, pull_request, workflow_dispatch]

jobs:
  build-linux:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build JAR
      run: ./mvnw -ntp -B clean package jpackage:jpackage@linux
      
    - name: Build AppImage
      uses: babaissarkar/jar-to-executable@v1
      with:
       id: "wml"
       name: "WML"
       icon: "./src/main/resources/wml.png"
       desktop-file: "./src/main/resources/wml.desktop"
       input: "./jar/wml.jar"
       output: "./WML.AppImage"

    - uses: actions/upload-artifact@v4
      with:
        name: wml.jar
        path: "./jar/wml.jar"
        
    - uses: actions/upload-artifact@v4
      with:
        name: wml.deb
        path: "./*.deb"
        
    - uses: actions/upload-artifact@v4
      with:
        name: WML.AppImage
        path: "./WML.AppImage"
        
    - name: Update release
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          ./jar/wml.jar
          ./WML.AppImage

  build-windows:

    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: ./mvnw -ntp -B clean package jpackage:jpackage@win
       
    - name: Create portable single-file Executable
      uses: babaissarkar/jar-to-executable@v1
      with:
       id: "wml"
       name: "WML"
       icon: "./src/main/resources/wml.ico"
       input: "./WML-Parser-LSP"
       output: "./wml.exe"
       
    - name: Upload built portable Executable
      uses: actions/upload-artifact@v4
      with:
        name: wml.exe
        path: ./wml.exe
